version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: chuukCarbon
      POSTGRES_USER: postgres
      POSTGRES_DB: test
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: chuukCarbon
